version: '2'
services:
  note_book_service:
    build: .
    ports:
      - "${TOMCAT_EXTERNAL_PORT}:8080"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_DOCKER_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'notebook'
      MYSQL_USER: 'notebook'
      MYSQL_PASSWORD: '${MYSQL_DOCKER_USER_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_docker_volumes/notebook:/var/lib/mysql
