version: '2'
services:
  note_book_service:
    build: .
    ports:
      - "${TOMCAT_EXTERNAL_PORT}:8080"
    volumes:
      - ./logs:/usr/local/tomcat/log

  mysql:
    image: hypriot/rpi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_DOCKER_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'notebook'
      MYSQL_USER: 'notebook'
      MYSQL_PASSWORD: '${MYSQL_DOCKER_USER_PASSWORD}'
    ports:
      - "3307:3306"
    volumes:
      - ~/mysql_docker_volumes/notebook:/var/lib/mysql
